task_config_store:
  _target_: rest_api.task_config_store.TaskConfigStore
  url: sqlite:///../obsei.db

task_scheduler:
  scheduler:
    _target_: apscheduler.schedulers.asyncio.AsyncIOScheduler
  jobstore:
    _target_: apscheduler.jobstores.memory.MemoryJobStore

analyzer:
  _target_: obsei.text_analyzer.TextAnalyzer
  # model_name_or_path: "joeddav/bart-large-mnli-yahoo-answers",
  # model_name_or_path: "/home/user/models/bart-large-mnli-yahoo-answers",
  model_name_or_path: '../../models/bart-large-mnli-yahoo-answers'
  initialize_model: true

rate_limiter:
  _target_: rest_api.rate_limiter.RequestLimiter
  concurrent_request_per_worker: 2

logging:
  base_config:
    level: DEBUG
    format: '%(asctime)s %(name)s:%(funcName)s [%(processName)s:%(threadName)s] %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S %Z'

hydra:
  run:
    # Output directory for normal runs
    dir: /tmp/outputs/${now:%Y-%m-%d_%H-%M-%S}