uvicorn:
  _target_: uvicorn.run
  host: 0.0.0.0
  port: 9898
  workers: 1
  reload: true
  app: rest_api.application:app

task_config_store:
  _target_: rest_api.task_config_store.TaskConfigStore
  url: sqlite:///../obsei.db

task_scheduler:
  scheduler:
    _target_: apscheduler.schedulers.asyncio.AsyncIOScheduler
  jobstore:
    _target_: apscheduler.jobstores.memory.MemoryJobStore

analyzer:
  _target_: obsei.text_analyzer.TextAnalyzer
  # model_name_or_path="joeddav/bart-large-mnli-yahoo-answers",
  # model_name_or_path="/home/user/models/bart-large-mnli-yahoo-answers",
  initialize_model: false

rate_limiter:
  _target_: rest_api.rate_limiter.RequestLimiter
  concurrent_request_per_worker: 2

logging:
  base_config:
    log_level: DEBUG
    format: '%(asctime)s %(name)s:%(funcName)s [%(processName)s:%(threadName)s] %(message)s'
    datefmt: '%d/%m/%Y %H:%M:%S %Z'

hydra:
  run:
    # Output directory for normal runs
    dir: /tmp/outputs/${now:%Y-%m-%d_%H-%M-%S}